
# Pandas Class 4 Assignment


# Q1. Select Single Column

## Problem Statement
Create a DataFrame and display only the Name column.

## Sample Input
```python
Name, Age
```

## Sample Output
```python
Only Name column
```

In [1]:
import pandas as pd
data = {
    "Name" : ["Aditi","Aadi","Rishi","Ansh"],
    "Age" : [18,22,24,21]
}
df = pd.DataFrame(data)
print(df['Name'])

0    Aditi
1     Aadi
2    Rishi
3     Ansh
Name: Name, dtype: str


# Q2. Select Multiple Columns

## Problem Statement
Display Name and Marks columns from a DataFrame.

## Sample Input
```python
Name, Marks
```

## Sample Output
```python
Selected columns
```

In [3]:
import pandas as pd
data = {
    "Name" : ["Aditi","Aadi","Rishi","Ansh"],
    "Marks" : [90,84,96,72]
}
df = pd.DataFrame(data)
print(df[['Name','Marks']])

    Name  Marks
0  Aditi     90
1   Aadi     84
2  Rishi     96
3   Ansh     72


# Q3. Filter Students

## Problem Statement
Display students with Marks greater than 80.

## Sample Input
```python
Marks > 80
```

## Sample Output
```python
Filtered rows
```

In [12]:
import pandas as pd
data = {
    "Name" : ["Aditi","Aadi","Rishi","Ansh"],
    "Marks" : [90,66,96,72]
}
df = pd.DataFrame(data)
df[df['Marks']  > 80]
# OR
# df.query("Marks > 80")

    Name  Marks
0  Aditi     90
2  Rishi     96


# Q4. Filter by City

## Problem Statement
Display students belonging to Bhopal.

## Sample Input
```python
City = Bhopal
```

## Sample Output
```python
Matching rows
```

In [3]:
import pandas as pd
data = {
    "Name" : ["Aditi","Aadi","Rishi","Ansh","Priya"],
    "City" : ["Bhopal","Delhi","Bhopal","Pune","Mumbai"]
}
df = pd.DataFrame(data)

df[df["City"] == "Bhopal"]

    Name    City
0  Aditi  Bhopal
2  Rishi  Bhopal


# Q5. Find Maximum Marks

## Problem Statement
Find the highest marks from a DataFrame.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Highest value
```

In [ ]:
import pandas as pd
data = {
    "Marks" : [90,66,96,72]
}
df = pd.DataFrame(data)
print(df['Marks'].max())

96


# Q6. Find Minimum Age

## Problem Statement
Find the minimum age.

## Sample Input
```python
Age column
```

## Sample Output
```python
Minimum age
```

In [7]:
import pandas as pd
data = {
    "Age" : [18,22,24,21]
}
df = pd.DataFrame(data)
print(df["Age"].min())

18


# Q7. Sort Data

## Problem Statement
Sort students by Marks.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Sorted DataFrame
```

In [9]:
import pandas as pd
data = {
    "Name" : ["Aditi","Aadi","Rishi","Ansh"],
    "Marks" : [90,66,96,72]
}
df = pd.DataFrame(data)

df.sort_values(by='Marks')

    Name  Marks
1   Aadi     66
3   Ansh     72
0  Aditi     90
2  Rishi     96


# Q8. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City column
```

## Sample Output
```python
Frequency count
```

In [10]:
import pandas as pd
data = {
    "City" : ["Bhopal","Pune","Delhi","Pune","Mumbai","Delhi"]
}
df = pd.DataFrame(data)

df['City'].value_counts()

City
Pune      2
Delhi     2
Bhopal    1
Mumbai    1
Name: count, dtype: int64


# Q9. Group By City

## Problem Statement
Find average marks city-wise.

## Sample Input
```python
City and Marks
```

## Sample Output
```python
Grouped result
```

In [11]:
import pandas as pd
data = {
    "City" : ["Bhopal","Delhi","Bhopal","Pune"],
    "Marks" : [90,66,96,72]
}
df = pd.DataFrame(data)

df.groupby('City')['Marks'].mean()

City
Bhopal    93.0
Delhi     66.0
Pune      72.0
Name: Marks, dtype: float64


# Q10. Multiple Conditions

## Problem Statement
Display students with Marks > 70 and Age > 20.

## Sample Input
```python
Marks and Age
```

## Sample Output
```python
Filtered rows
```

In [12]:
import pandas as pd
data = {
    "Name" : ["Aditi","Aadi","Rishi","Ansh"],
    "Age" : [18,22,19,21],
     "Marks" : [90,66,96,72]   
}
df = pd.DataFrame(data)

df[(df['Marks'] > 70) & (df['Age'] > 20)]

   Name  Age  Marks
3  Ansh   21     72